version: '2'
services:
  rabbitmq:
    image: "rabbitmq:3.8-management"
    ports:
    - 5672:5672
    - 15672:15672
  vault:
    image: "vault:1.6.0"
    environment:
    - VAULT_DEV_ROOT_TOKEN_ID=myroot
    cap_add:
    - IPC_LOCK
    ports:
    - 8200:8200
    volumes:
    - "./vault/file:/vault/file"
    - "./vault/logs:/vault/logs"